### ISSUE TITLE
Install Nextcloud on the server

### ISSUE THREAD

**Issue by arikalfus** [arikalfus/nextcloud-ansible#1]
~https://doc.owncloud.org/desktop/2.2/installing.html~
~https://doc.owncloud.org/desktop/2.2/building.html#linux~

Those are for the desktop client. We want the server below:
https://civihosting.com/blog/how-to-install-nextcloud-server/
https://nextcloud.com/install/#instructions-server

https://docs.nextcloud.com/server/12/admin_manual/installation/source_installation.html#prerequisites-for-manual-installation

Important link:
https://help.nextcloud.com/t/linux-packages-status/10216

**Comment by abefleming** [comment]
[In case you want to expand the storage partition](https://serverfault.com/questions/861517/centos-7-extend-partition-with-unallocated-space)

**Comment by abefleming** [comment]
[If SELinux gets in your way](https://blog.lysender.com/2015/07/centos-7-selinux-php-apache-cannot-writeaccess-file-no-matter-what/)

**Comment by arikalfus** [comment]
https://www.howtoforge.com/tutorial/how-to-install-nextcloud-with-nginx-and-php-fpm-on-centos-7/
https://civihosting.com/blog/how-to-install-nextcloud-server/

**Comment by arikalfus** [comment]
Don't know how I didn't find this earlier: https://docs.nextcloud.com/server/12/admin_manual/configuration_server/occ_command.html#command-line-installation-label

**Comment by arikalfus** [comment]
Implemented in #40
