### ISSUE TITLE
Utilize Nginx in place of Apache in the default LAMP stack for Nextcloud Installation

### ISSUE THREAD

**Issue by abefleming** [arikalfus/nextcloud-ansible#13]

**Comment by arikalfus** [comment]
https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-centos-7

**Comment by arikalfus** [comment]
https://www.nginx.com/blog/free-certificates-lets-encrypt-and-nginx/

**Comment by arikalfus** [comment]
Implemented in #16
