### ISSUE TITLE
Configure php.ini

### ISSUE THREAD

**Issue by arikalfus** [arikalfus/nextcloud-ansible#20]
I am not familiar with PHP at all. I am going to configure the `php.ini` file according to NextCloud's documentation and reading through the options myself to choose best practices, but the default file is very large. Would appreciate help securely and correcting setting up the `php.ini` file.

https://github.com/arikalfus/nextcloud-ansible/blob/master/files/php/php.ini.j2

**Comment by abefleming** [comment]
I have not needed to configure or change anything in php.ini, nor have I had to modify it. I will see what I can provide as to setting specific values and how they translate post installation.

**Comment by arikalfus** [comment]
Ok, good to know. There are likely sensible defaults we would want to modify if the Nextcloud server is intended to be accessible from the public internet. But I can ignore that for the time being.
