### ISSUE TITLE
Using dsaparam instead of generator options

### ISSUE THREAD

**Issue by abefleming** [arikalfus/nextcloud-ansible#26]
Openssl allows the usage of `-dsaparam` in the place of the recommended `-2` or `-5`. Runtime is significantly reduced with `-dsaparam`, but there is a concern of the strength of using dsa parameters instead and should be investigated.

**Comment by arikalfus** [comment]
Honestly, that needs to be re-done to generate ECDH parameters instead of DH parameters.
