### ISSUE TITLE
Support per-host sudo_password

### ISSUE THREAD

**Issue by arikalfus** [arikalfus/nextcloud-ansible#65]
Currently, if more than one system is provisioned, they all must have the same root account passwords. This is not ideal.

Have to think about how this can be built, as Ansible does not support this. I'm thinking that the best method is to import a Vault-encrypted variable file based on either the `ansible_distribution`, which would let us have different sudo passwords per-OS type, or by `ansible_user`, which would let us have different sudo passwords per non-privileged user account. The latter is likely to be more unique across different systems (or can be intentionally constructed to be unique pretty easily) so I'm in favor of implementing that to accommodate separate sudo password variables.

**Comment by arikalfus** [comment]
By sudo I meant whatever `become_method` is used for that OS, e.g. `su` for Debian. I'm referring to the `sudo_password` secret variable.

**Comment by abefleming** [comment]
The `sudo_password` variable is the password for the root account, or for the user to enact sudo?

**Comment by abefleming** [comment]
I am thinking something akin to a password/shadow file would be useful here. It can have multiple entries, with each entry containing multiple attributes which can be associated to host, user, distro, etc. 

It is late at the moment and I have not had my late night coffee.

**Comment by arikalfus** [comment]
Yeah, that's basically what I'm going for with this issue. Good to know my intuition is aligned with yours.
